timing_report = (
    "=== Timing Report: crossbar_mac\n"
    "=== Tool: Yosys 0.52 + ABC  |  Library: generic_130nm (130 nm educational)\n"
    "=== Clock target: 10.00 ns (100 MHz)  |  Date: 2026-05-17\n"
    "\n"
    "--- ABC stime Report (from synth.log step 13: abc -liberty -D 10000 -constr) ---\n"
    "\n"
    "  WireLoad = \"none\"   Gates = 1476 (8.9%)   Area = 3267.00   Delay = 5380.00 ps\n"
    "\n"
    "  Timing status: CLOSED\n"
    "    Current delay (5380.00 ps) does not exceed target (10000.00 ps).\n"
    "    Upsizing not performed.\n"
    "\n"
    "  Critical Path (21 stages, primary-input -> primary-output):\n"
    "    Stage  0  in0[1]        --  primary input (activation bit)\n"
    "    Stage  1  MUX2   x4     Df =  630.0 ps   weight-gated add/sub mux\n"
    "    Stage  2  XNOR2  x3     Df =  980.0 ps   partial sum XOR bits 0..2\n"
    "    Stage  3  AOI21  x2     Df = 1140.0 ps   carry generate\n"
    "    Stage  4  OAI21  x2     Df = 1340.0 ps   carry propagate\n"
    "    Stage  5  MUX2   x1     Df = 1620.0 ps   partial sum mux\n"
    "    Stage  6  XNOR2  x6     Df = 1970.0 ps   bits 3..8 sum\n"
    "    Stage  7  XNOR2  x1     Df = 2320.0 ps   bit 9 sum\n"
    "    Stage  8  AOI21  x2     Df = 2480.0 ps   carry gen bits 9..10\n"
    "    Stage  9  OAI21  x2     Df = 2680.0 ps   carry prop bits 9..10\n"
    "    Stage 10  MUX2   x1     Df = 2960.0 ps   sum mux bit 11\n"
    "    Stage 11  XNOR2  x5     Df = 3310.0 ps   bits 12..16 sum\n"
    "    Stage 12  XNOR2  x1     Df = 3660.0 ps   bit 17 sum\n"
    "    Stage 13  OAI21  x2     Df = 3820.0 ps   carry prop bits 17..18\n"
    "    Stage 14  AOI21  x2     Df = 4020.0 ps   carry gen bits 19..20\n"
    "    Stage 15  OAI21  x2     Df = 4180.0 ps   carry prop bits 19..20\n"
    "    Stage 16  AOI21  x1     Df = 4380.0 ps   carry gen bit 21\n"
    "    Stage 17  XNOR2  x2     Df = 4730.0 ps   bits 22..23 sum\n"
    "    Stage 18  MUX2   x4     Df = 5010.0 ps   output select mux\n"
    "    Stage 19  BUF    x10    Df = 5140.0 ps   fanout buffer\n"
    "    Stage 20  AND2   x1     Df = 5380.0 ps   output enable / mux\n"
    "\n"
    "    Start-point: in0[1]  (DFFR Q, bit 1 of activation input 0)\n"
    "    End-point  : MuxGate DFF D input (output register data path)\n"
    "\n"
    "--- Derived Register-to-Register Timing ---\n"
    "\n"
    "  Combinational delay (abc stime) :  5.38 ns\n"
    "  DFFR clock-to-Q (Q timing arc)  : +0.30 ns\n"
    "  DFF setup time (130 nm est.)    : +0.18 ns\n"
    "                                   ----------\n"
    "  Total register-to-register path :  5.86 ns\n"
    "  Clock period                    : 10.00 ns\n"
    "  Worst-case slack (WNS)          : +4.14 ns  POSITIVE -- TIMING MET\n"
    "\n"
    "  Maximum achievable frequency    : ~171 MHz  (1 / 5.86 ns)\n"
    "\n"
    "--- Note on Yosys Built-in STA ---\n"
    "\n"
    "  Yosys 0.52 sta does not recognise liberty-mapped cell names (AND2, NAND2...).\n"
    "  All cells logged as 'not recognised -- ignoring.'\n"
    "  The ABC stime report above is the authoritative timing source.\n"
    "  Full synthesis log (including ABC output) saved in synth.log.\n"
)

with open('/mnt/c/Users/Husai/Ece-410-hardware-ai/codefest/cf07/synth/timing_report.txt', 'w', newline='\n') as f:
    f.write(timing_report)
print('timing_report.txt written ({} lines)'.format(len(timing_report.splitlines())))
